### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by radiophonic** [DaylightingSociety/SocMap#31]
Hi there, initial startup of the program fails. 

```
./socmap.py -a auth.txt -u userlist.txt -l 2

09/25/22 13:24:13 Info: Beginning data collection for layer 0
Traceback (most recent call last):
  File "/home/snafu/Tools/SocMap/acquire.py", line 26, in limit_handled
    yield cursor.next()
  File "/home/snafu/.local/lib/python3.8/site-packages/tweepy/cursor.py", line 286, in next
    self.current_page = next(self.page_iterator)
  File "/home/snafu/.local/lib/python3.8/site-packages/tweepy/cursor.py", line 86, in __next__
    return self.next()
  File "/home/snafu/.local/lib/python3.8/site-packages/tweepy/cursor.py", line 190, in next
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./socmap.py", line 114, in <module>
    acquire.getLayers(api, options.layers, options, layer0)
  File "/home/snafu/Tools/SocMap/acquire.py", line 167, in getLayers
    getUserTweets(api, username, options.tweetdir, options.numtweets, options.compress)
  File "/home/snafu/Tools/SocMap/acquire.py", line 101, in getUserTweets
    for tweet in limit_handled(api, cursor.items()):
  File "/home/snafu/Tools/SocMap/acquire.py", line 27, in limit_handled
    except tweepy.error.TweepError as e:
AttributeError: module 'tweepy' has no attribute 'error'
```
Any suggestions?

**Comment by milo-trujillo** [comment]
I'm not surprised: the download code hasn't been updated in three years, and the Tweepy API has changed in that time, in part because the underlying Twitter API has changed in that time. Unless/until someone makes a pull request to bring `acquire.py` up to parity with Tweepy, this codebase should be considered non-functional. Well, the analysis tools will still work with any data that's already been downloaded, but it won't be able to fetch any new tweets. I'm not maintaining this code at this time, so it'd take some external contributions.
